### ISSUE TITLE
[BUG] Algebra unstable before a create table

### ISSUE THREAD

**Issue by mario21ic** [BlazingDB/pyBlazing#104]
**Describe the bug**
Calcite gets unstable after I run a create table only put the table name and file path.

**Steps/Code to reproduce bug**
When I create a table with the following code:
```
bc.create_table('nation', table_list)
```
I mean, without these params: delimiter='|', dtype=column_types, names=column_names

**Expected behavior**
The SQL script must be executed correctly.

**Environment overview (please complete the following information)**
Docker

**Additional context**
I got this error message on Algebra:
```
ERROR: org.hibernate.AssertionFailure - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
org.hibernate.AssertionFailure: null id in com.blazingdb.calcite.catalog.domain.CatalogColumnImpl entry (don't flush the Session after an exception occurs)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:82)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:190)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:147)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:219)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:99)
        at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
        at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
        at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
        at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
        at com.blazingdb.calcite.catalog.repository.DatabaseRepository.createDatabase(DatabaseRepository.java:58)
        at com.blazingdb.calcite.catalog.repository.DatabaseRepository.updateDatabase(DatabaseRepository.java:156)
        at com.blazingdb.calcite.catalog.connection.CatalogServiceImpl.dropTable(CatalogServiceImpl.java:36)
        at com.blazingdb.calcite.application.CalciteService.processRequest(CalciteService.java:78)
        at com.blazingdb.calcite.application.TCPService.run(TCPService.java:134)
        at java.base/java.lang.Thread.run(Thread.java:834)
Waiting for messages in TCP port: 8890
```

I think pyBlazing should verify the params before executing the SQL script.

**Comment by aucahuasi** [comment]
Hi @mario21ic thanks, we are going to look into this issue! +1

**Comment by Christian8491** [comment]
@mario21ic  pyblazing already verify params. For this case, pyblazing is smart enough to know what delimiter should use with the extension _.psv_. Also can detect smartly dtypes. I cannot reproduced this bug. Can you write the exactly script which reports this bug? 
So, please let me know if this bug appear again. cc @aucahuasi

**Comment by aucahuasi** [comment]
Thanks @Christian8491 @mario21ic +1
